// client/react-redux/src/components/overview/stats/Stats.js
import { MenuItem, Select } from '@material-ui/core';
import { FormControl, InputLabel } from '@material-ui/core';
import React, { useEffect, useState } from 'react';
import { useSelector } from 'react-redux'
import { months, httpOptions } from '../../../utils/common'

import  './Stats.css'

function Stats() {

  const result = useSelector( state => {
    console.log(state.stats)
    return state.stats
  })

  const [stats, setStats] = useState([])

  const [year, setYear] = useState('2020');

  const urlStats = `https://api.covid19api.com/total/country/${result}`

  const handleChange = (event) => {
    setYear(event.target.value);
  };

  const createObjArr = () => {

    if (result) {
      fetch(urlStats, httpOptions('GET'))
          .then((response) => response.json())
          .then((data) => {
              const objArrAux = []

              //assembly an object to populate the list
              months.map((el) => { 
                const date = `${year}-${el.number}-28T00:00:00Z`
                const objFound = data.find((el) => el.Date === date)
                if (objFound === undefined) {
                  objArrAux.push(
                    {
                      Month: el.text,
                      Confirmed: 0,
                      Deaths: 0
                    }
                  )
                } else {
                  objArrAux.push(
                    {
                      Month: el.text,
                      Confirmed: objFound.Confirmed,
                      Deaths: objFound.Deaths
                    }
                  )
                }
              })
              setStats(objArrAux)
          })
          .catch(err => {
            console.log(err)
          }) 
    }
  }

  useEffect(() => {
    createObjArr()
  }, [year])

  return (
    <div className='main-stats'>
      <div className='select'>
        <FormControl variant="outlined" >
          <InputLabel id="demo-simple-select-outlined-label">Year</InputLabel>
          <Select
            labelId="demo-simple-select-outlined-label"
            id="demo-simple-select-outlined"
            value={year}
            onChange={handleChange}
            label="Year"
            className='year'
          >
            <MenuItem value={2020}>2020</MenuItem>
            <MenuItem value={2021}>2021</MenuItem>
          </Select>
        </FormControl>
      </div>
      
      <div className="panel-stats">
        <span className='title-panel-stats'>Cases/Deaths Montly</span>
        
        {stats.map((el) => {  
           return (
            <div className='row-stats' key={el.Month}>
              <span className='row-month'>{el.Month}</span>
              <span className='row-value'>{el.Confirmed.toLocaleString('de-DE')}</span>
              <span className='row-amount'>{el.Deaths.toLocaleString('de-DE')}</span>
            </div>
           ) 
        })}
      </div>  
    </div>  
  )
}

export default Stats;

// client/angular-covid/src/app/overview/stats/stats.component.ts
import { SimpleChanges } from '@angular/core';
import { Component, Input, OnInit } from '@angular/core';
import { GlobalService } from 'src/app/global.service';

@Component({
  selector: 'app-stats',
  templateUrl: './stats.component.html',
  styleUrls: ['./stats.component.css']
})
export class StatsComponent implements OnInit {

  year = 2020;
  @Input() country: string
  stats: any[]
  urlStats: string

  constructor(private globalService: GlobalService) { }

  ngOnInit(): void {}

  ngOnChanges() {
    this.createStats()
  }

  clickRadio(param) {
    this.year = param
    this.createStats()
  }

  createStats() {
    const urlStats = `https://api.covid19api.com/total/country/${this.country}`

    if (this.country) {

      const dataStats = this.globalService.fetchStats(urlStats)
      dataStats.subscribe((res: any) => { 

        const objArrAux = []

        this.globalService.months.map((el) => { 
          const date = `${this.year}-${el.number}-28T00:00:00Z`
          const objFound = res.find((el) => el.Date === date)
          if (objFound === undefined) {
            objArrAux.push(
              {
                Month: el.text,
                Confirmed: 0,
                Deaths: 0
              }
            )
          } else {
            objArrAux.push(
              {
                Month: el.text,
                Confirmed: objFound.Confirmed,
                Deaths: objFound.Deaths
              }
            )
          }
        })
        this.stats = objArrAux
      })
    }

  }

}

<div class='main-stats'>
    <div class='select'>
      <h3>select</h3>
      <div class="btn-group btn-group-toggle" ngbRadioGroup name="radioBasic" [(ngModel)]="year">
        <label ngbButtonLabel class="btn-primary">
          <input ngbButton type="radio" [value]="2020" (click)="clickRadio('2020')">2020
        </label>
        <label ngbButtonLabel class="btn-primary">
          <input ngbButton type="radio" [value]="2021" (click)="clickRadio('2021')">2021
        </label>
      </div>
    </div>
    
    <div class="panel-stats">
      <span class='title-panel-stats'>Cases/Deaths Montly</span>
      
      <div class='row-stats' *ngFor="let el of stats">
        <span class='row-month'>{{el.Month}}</span>
        <span class='row-value'>{{el.Confirmed | number:'1.0':'de' }}</span>
        <span class='row-amount'>{{el.Deaths | number:'1.0':'de' }}</span>
      </div>
    </div>  
  </div>
