// client/react-redux-covid/src/components/volunteer/Volunteer.js
import React, { useState, useEffect } from 'react';
import { DataGrid } from '@material-ui/data-grid'
import './Volunteer.css'
import { Button, IconButton, TextField } from '@material-ui/core';
import { Edit } from '@material-ui/icons';
import DeleteIcon from '@material-ui/icons/Delete';
import { url_volunteer, httpOptions, httpOptionsBody } from '../../utils/common'


function Volunteer() {

  const initialFormState = { name: '', email: '', phone: '' }
  const [volunteers, setVolunteers] = useState([])
  const [volunteer, setVolunteer] = useState(initialFormState)
  const [fromEdit, setFromEdit] = useState(false)
  const [id, setId] = useState()

  const handleInputChange = (event) => {
    const { name, value } = event.target
    setVolunteer({ ...volunteer, [name]: value })
  }

  const getVolunteer = async () => {

    const objArrAux = []

    await fetch(url_volunteer, httpOptions('GET'))
      .then((response) => response.json())
      .then((data) => {
        //assembly an object to populate the list
        data.map((el) => {
          objArrAux.push(
            {
              id: el._id,
              name: el.name,
              email: el.email,
              phone: el.phone,
            }
          )
        })
      })
      .catch(err => {
        console.log(err)
      })
    setVolunteers(objArrAux)
  }

  const saveVolunteer = () => {

    if (!fromEdit) {
      
      fetch(url_volunteer, httpOptionsBody('POST', volunteer))
      .then((response) => response.json())
      .then(() => {
        getVolunteer()
        setVolunteer(initialFormState)
      })
    } else {
      fetch(`http://localhost:5000/volunteer/${id}`, httpOptionsBody('PATCH', volunteer))
      .then((response) => response.json())
      .then(() => {
        getVolunteer()
        setVolunteer(initialFormState)
      })
    }

    
    setFromEdit(false)
  }

  //Data-grid columns definition
  const columns = [
    { field: 'id', headerName: 'ID', hide: true },
    { field: 'name', headerName: 'Name', width: 300 },
    { field: 'email', headerName: 'email', width: 350 },
    { field: 'phone', headerName: 'phone', width: 200 },
    {
      field: "",
      headerName: "Actions",
      sortable: false,
      width: 120,
      disableClickEventBubbling: true,
      renderCell: (params) => {
        const onEdit = () => {
          const api = params.api;
            const fields = api
              .getAllColumns()
              .map((c) => c.field)
              .filter((c) => c !== "__check__" && c !== "id" && !!c );
            
            const thisRow = {};  
    
            fields.forEach((f) => {
              thisRow[f] = params.getValue(f);
            });

            setFromEdit(true)
            setId(params.row.id)
            setVolunteer(thisRow)
            /* return alert(JSON.stringify(thisRow, null, 4)); */
        }
        const onDelete = () => {
          fetch(`http://localhost:5000/volunteer/${params.row.id}`, httpOptions('DELETE'))
            .then((response) => response.json())
            .then(() => {
              getVolunteer()
            })
        }
        return (
          <div>
            <IconButton color="primary" component="span" onClick={onEdit}>
              <Edit />
            </IconButton>
            <IconButton color="primary" component="span" onClick={onDelete}>
              <DeleteIcon />
            </IconButton>
          </div>
        );
      }
    }
  ]

  useEffect(() => {
    getVolunteer()
  }, [])


  return (
    <div className='main-volunteer'>
      <div className='add-volunteer'>
        <h4>Volunteer</h4>
        <div className="panel-stats-volunteer">
          <span className='title-panel-stats'>Volunteer Form</span>
            <TextField id="name-field" label="Name" className='volunteer-field' name="name" value={volunteer.name} onChange={handleInputChange} />
            <TextField id="email-field" label="Email" className='volunteer-field' name="email" value={volunteer.email} onChange={handleInputChange} />
            <TextField id="phone-field" label="Phone" className='volunteer-field' name="phone" value={volunteer.phone} onChange={handleInputChange} />
            <Button variant="contained" color="primary" type="submit" onClick={saveVolunteer}>
              Save
            </Button>
        </div>
      </div>

      <div className='volunteer-list'>
        <span className='title-panel-stats'>Volunteer List</span>
        <DataGrid rows={volunteers} columns={columns} pageSize={10} className='datatable' />
      </div>


    </div>
  );
}

export default Volunteer;

// client/angular-covid/src/app/volunteer/volunteer.component.ts
import { Component, OnInit } from '@angular/core';
import { GlobalService } from '../global.service';

interface IVolunteer {
  id: string
  name: string;
  email: string;
  phone: string;
}

@Component({
  selector: 'app-volunteer',
  templateUrl: './volunteer.component.html',
  styleUrls: ['./volunteer.component.css']
})



export class VolunteerComponent implements OnInit {

  id: string
  name: string
  email: string
  phone: string
  volunteers: IVolunteer[] = []
  isLoading: boolean = false
  fromEdit: boolean = false


  constructor(private globalService: GlobalService) { }

  ngOnInit(): void {
    this.fetchVolunteerList()
  }

  fetchVolunteerList() {
    this.isLoading = true

    const volunteerData = this.globalService.getVolunteer()
    volunteerData.subscribe((res: any) => {

      const objArrAux: IVolunteer[] = []

      res.map((el) => {
        objArrAux.push(
          {
            id: el._id,
            name: el.name,
            email: el.email,
            phone: el.phone,
          }
        )
      })

      this.volunteers = objArrAux
    })

    this.isLoading = false
  }

  onEdit(id, name, email, phone) {
    this.id = id
    this.name = name
    this.email = email
    this.phone = phone
    this.fromEdit = true
  }

  onDelete(id) {
    this.globalService.deleteVolunteer(id)
      .subscribe((res) => {
        this.fetchVolunteerList()
      }, err => {
       console.log('post volunteer', err)
      });
  }

  saveVolunteer() {
    const body = {
      name: this.name, 
      email: this.email,
      phone: this.phone
    }


      if (!this.fromEdit) {
        this.globalService.postVolunteer(body)
        .subscribe((res) => {
          this.fetchVolunteerList()
          this.cleanFields()
        }, err => {
         console.log('post volunteer', err)
        });

      } else {
        this.globalService.putVolunteer(this.id, body)
        .subscribe((res) => {
          this.fetchVolunteerList()
          this.cleanFields()
        }, err => {
         console.log('post volunteer', err)
        });
      }

  }

  cleanFields() {
    this.name = ''
    this.email = ''
    this.phone = ''
  }

}

<div class='main-volunteer'>
    <div class='add-volunteer'>
        <h4>Volunteer</h4>
        <div class="panel-stats-volunteer">
            <span class='title-panel-stats'>Volunteer Form</span>
                <input id="name-field" type="text" class='form-control' name="name" [(ngModel)]="name" placeholder="Name" required>
                <input id="email-field" type="text" class='form-control' name="email" [(ngModel)]="email" placeholder="Email" required>
                <input id="phone-field" type="text" class='form-control' name="phone" [(ngModel)]="phone" placeholder="Phone" required>
                <button class="form-control btn btn-outline-primary" type="submit" id="button-addon2" (click)="saveVolunteer()">
                    <mat-icon aria-hidden="false" aria-label="Example search icon" >save</mat-icon>
                </button>
        </div>
    </div>

    <div class='volunteer-list'>
        <span class='title-panel-stats'>Volunteer List</span>
        <table class="table table-striped">
            <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Name</th>
              <th scope="col">Email</th>
              <th scope="col">Phone</th>
              <th scope="col" colspan="2">Actions</th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let volunteer of volunteers">
              <th scope="row" hidden>{{ volunteer.id }}</th>
              <td>
                {{ volunteer.name }}
              </td>
              <td>
                {{ volunteer.email }}
              </td>
              <td>
                {{ volunteer.phone }}
              </td>
              <td>
                <button class="form-control btn btn-sm btn-outline-primary" type="button" id="button-addon2" (click)="onEdit(volunteer.id, volunteer.name, volunteer.email, volunteer.phone)"
                    ><mat-icon aria-hidden="false" aria-label="Example search icon">edit</mat-icon></button>
              </td>
              <td>
                <button class="form-control btn btn-sm btn-outline-primary" type="button" id="button-addon2" (click)="onDelete(volunteer.id)"
                    ><mat-icon aria-hidden="false" aria-label="Example search icon">delete</mat-icon></button>
              </td>
            </tr>
            </tbody>
          </table>
          
    </div>
</div>
