// client/react-redux-covid/src/components/overview/Overview.js
import React, { useState, useEffect } from 'react';
import { useDispatch } from 'react-redux'
import Stats from './stats/Stats';
import Autocomplete from '@material-ui/lab/Autocomplete';
import { TextField, CircularProgress } from '@material-ui/core';
import { url_data, httpOptions } from '../../utils/common'
import { selectCountry } from '../../redux/Stats.actions'

import './Overview.css';

function Overview() {

  const dispatch = useDispatch()

  const [country, setCountry] = useState('')
  const [countries, setCountries] = useState([])
  const [isLoading, setIsLoading] = useState(false)
  const [totalConfirmed, setTotalConfirmed] = useState(0)
  const [totalRecovered, setTotalRecovered] = useState(0)
  const [totalDeath, setTotalDeath] = useState(0)
  const [totalActive, setTotalActive] = useState(0)
  const [percentRecovered, setPercentRecovered] = useState(0)
  const [percentDeath, setPercentDeath] = useState(0)
  const [percentActive, setPercentActive] = useState(0)
  const [newConfirmed, setNewConfirmed] = useState(0)
  const [newDeath, setNewDeath] = useState(0)
  const [newRecovered, setNewRecovered] = useState(0)
  const [newActive, setNewActive] = useState(0)

  const handleChangeCountry = (event, newValue) => {
      setCountry(newValue);
      (newValue !== null) ? fetchDataCountry(url_data, newValue) : fetchDataGlobal(url_data)
      dispatch(selectCountry(newValue))
      
  }

  const fetchCountryList = async (url) => {
    await fetch(url, httpOptions('GET'))
      .then((response) => response.json())
      .then((data) => {
        setCountries((data.Countries.map((el) => el.Country)).sort())
      })
      .catch(err => {
        console.log(err)
      })
  }

  const fetchDataGlobal = async (url) => {
    setIsLoading(true)

    await fetch(url, httpOptions('GET'))
      .then((response) => response.json())
      .then((res) => {
        setTotalConfirmed(res.Global.TotalConfirmed)
        setTotalRecovered(res.Global.TotalRecovered)
        setTotalDeath(res.Global.TotalDeaths)
        setTotalActive(res.Global.TotalConfirmed - res.Global.TotalRecovered - res.Global.TotalDeaths)
        setPercentRecovered(res.Global.TotalRecovered / res.Global.TotalConfirmed * 100)
        setPercentDeath(res.Global.TotalDeaths / res.Global.TotalConfirmed * 100)
        setPercentActive(100 - (res.Global.TotalDeaths / res.Global.TotalConfirmed * 100) - (res.Global.TotalRecovered / res.Global.TotalConfirmed * 100))
        setNewConfirmed(res.Global.NewConfirmed)
        setNewDeath(res.Global.NewDeaths)
        setNewRecovered(res.Global.NewRecovered)
        setNewActive(res.Global.NewConfirmed - res.Global.NewDeaths - res.Global.NewRecovered)
        setIsLoading(false)
      })
      .catch(err => {
        console.log(err)
        alert(err)
      })
  }

  const fetchDataCountry = async (url, newValue) => {
    setIsLoading(true)

    await fetch(url, httpOptions('GET'))
      .then((response) => response.json())
      .then((res) => {

        const obj = res.Countries.find((el) => el.Country === newValue)

        setTotalConfirmed(obj.TotalConfirmed)
        setTotalRecovered(obj.TotalRecovered)
        setTotalDeath(obj.TotalDeaths)
        setTotalActive(obj.TotalConfirmed - obj.TotalRecovered - obj.TotalDeaths)
        setPercentRecovered(obj.TotalRecovered / obj.TotalConfirmed * 100)
        setPercentDeath(obj.TotalDeaths / obj.TotalConfirmed * 100)
        setPercentActive(100 - (obj.TotalDeaths / obj.TotalConfirmed * 100) - (obj.TotalRecovered / obj.TotalConfirmed * 100))
        setNewConfirmed(obj.NewConfirmed)
        setNewDeath(obj.NewDeaths)
        setNewRecovered(obj.NewRecovered)
        setNewActive(obj.NewConfirmed - obj.NewDeaths - obj.NewRecovered)
        setIsLoading(false)
      })
      .catch(err => {
        console.log(err)
        alert(err)
      })
  }

  useEffect(() => {
    fetchCountryList(url_data)
    fetchDataGlobal(url_data)
  }, [])

  return (
    <div>
      {isLoading ? (
        <div className='main-overview'>
          <CircularProgress className='loading' />
        </div>

      ) : (
            <div className='main-overview'>
              <div className='overview'>
                <h4>Overview</h4>
                <Autocomplete
                  value={country}
                  onChange={handleChangeCountry}
                  id="country-select"
                  options={countries}
                  style={{ width: 300 }}
                  renderInput={(params) => <TextField {...params} label="Select a Country" variant="outlined" className="country-textfield" />}
                />

                <div className="panel-overview">

                  <div className='paper-first'>
                    <div className='card-total'>
                      <span className='title'>Total Cases</span>
                      <span className='value'>{totalConfirmed.toLocaleString('de-DE')}</span>
                      <div className='total-new'>
                         <span className='text-new'>+{newConfirmed.toLocaleString('de-DE')}</span>
                      </div>
                    </div>

                  </div>

                  <div className='paper-second'>
                    <div className='card-active'>
                      <div>
                        <span className='title'>Active</span>
                        <span className='percent'>{parseFloat(percentActive.toString()).toFixed(2) + "%"}</span>
                      </div>
                      <span className='value'>{totalActive.toLocaleString('de-DE')}</span>
                      <div className='active-new'>
                        <span className='text-new'>{(newActive > 0) && '+' }{newActive.toLocaleString('de-DE')}</span>
                      </div>
                    </div>
                    <div className='card-recovered'>
                      <div>
                        <span className='title'>Recovered</span>
                        <span className='percent'>{parseFloat(percentRecovered.toString()).toFixed(2) + "%"}</span>
                      </div>
                      <span className='value'>{totalRecovered.toLocaleString('de-DE')}</span>
                      <div className='recovered-new'>
                        <span className='text-new'>+{newRecovered.toLocaleString('de-DE')}</span>
                      </div>
                    </div>
                    <div className='card-death'>
                      <div>
                        <span className='title'>Death</span>
                        <span className='percent'>{parseFloat(percentDeath.toString()).toFixed(2) + "%"}</span>
                      </div>
                      <span className='value'>{totalDeath.toLocaleString('de-DE')}</span>
                      <div className='death-new'>
                        <span className='text-new'>+{newDeath.toLocaleString('de-DE')}</span>
                      </div>
                    </div>
                  </div>

                </div>

              </div>
              <div className='stats'>
                {country && <Stats />}
              </div>
            </div>
        )}
    </div>



  );
}

export default Overview;

// client/angular-covid/src/app/overview/overview.component.ts
import { ViewChild } from '@angular/core';
import { Component, OnInit } from '@angular/core';
import { GlobalService } from '../global.service';
import {NgbTypeahead} from '@ng-bootstrap/ng-bootstrap';
import {Observable, Subject, merge} from 'rxjs';
import {debounceTime, distinctUntilChanged, filter, map} from 'rxjs/operators';
import { global } from '@angular/compiler/src/util';

@Component({
  selector: 'app-overview',
  templateUrl: './overview.component.html',
  styleUrls: ['./overview.component.css'],
  providers: [GlobalService]
})
export class OverviewComponent implements OnInit {

  country: string
  countries: any
  isLoading: boolean = false
  totalConfirmed: number
  totalRecovered: number
  totalDeath: number
  totalActive: number
  percentRecovered: number
  percentDeath: number
  percentActive: number
  newConfirmed: number
  newDeath: number
  newRecovered: number
  newActive: number

  constructor(private globalService: GlobalService) { }

  ngOnInit(): void {
    this.fetchDataGlobal()
  }

  @ViewChild('instance', {static: true}) instance: NgbTypeahead;
  focus$ = new Subject<string>();
  click$ = new Subject<string>();

  search = (text$: Observable<string>) => {
    const debouncedText$ = text$.pipe(debounceTime(200), distinctUntilChanged());
    const clicksWithClosedPopup$ = this.click$.pipe(filter(() => !this.instance.isPopupOpen()));
    const inputFocus$ = this.focus$;

    return merge(debouncedText$, inputFocus$, clicksWithClosedPopup$).pipe(
      map(term => (term === '' ? this.countries
        : this.countries.filter(v => v.toLowerCase().indexOf(term.toLowerCase()) > -1)).slice(0, 10))
    );
  }

  fetchDataCountry() {
    
    this.isLoading = true
    const globalData = this.globalService.getData()
    globalData.subscribe((res: any) => {

      const obj = res.Countries.find((el) => el.Country === this.country)

      if (obj === undefined) {
        alert("Não foi possível encontrar o país")
      } else {
        this.totalConfirmed = obj.TotalConfirmed
        this.totalRecovered = obj.TotalRecovered
        this.totalDeath = obj.TotalDeaths
        this.totalActive = obj.TotalConfirmed - obj.TotalRecovered - obj.TotalDeaths
        this.percentRecovered = obj.TotalRecovered / obj.TotalConfirmed * 100
        this.percentDeath = obj.TotalDeaths / obj.TotalConfirmed * 100
        this.percentActive = 100 - (obj.TotalDeaths / obj.TotalConfirmed * 100) - (obj.TotalRecovered / obj.TotalConfirmed * 100)
        this.newConfirmed = obj.NewConfirmed
        this.newDeath = obj.NewDeaths
        this.newRecovered = obj.NewRecovered
        this.newActive = obj.NewConfirmed - obj.NewDeaths - obj.NewRecovered
      }
    })
    this.isLoading = false


  }

  fetchDataGlobal() {

    this.isLoading = true

    const globalData = this.globalService.getData()
    globalData.subscribe((res: any) => {
      this.countries = this.globalService.fetchCountryList(res)
      this.totalConfirmed = res.Global.TotalConfirmed
      this.totalRecovered = res.Global.TotalRecovered
      this.totalDeath = res.Global.TotalDeaths
      this.totalActive = res.Global.TotalConfirmed - res.Global.TotalRecovered - res.Global.TotalDeaths
      this.percentRecovered = res.Global.TotalRecovered / res.Global.TotalConfirmed * 100
      this.percentDeath = res.Global.TotalDeaths / res.Global.TotalConfirmed * 100
      this.percentActive = 100 - (res.Global.TotalDeaths / res.Global.TotalConfirmed * 100) - (res.Global.TotalRecovered / res.Global.TotalConfirmed * 100)
      this.newConfirmed = res.Global.NewConfirmed
      this.newDeath = res.Global.NewDeaths
      this.newRecovered = res.Global.NewRecovered
      this.newActive = res.Global.NewConfirmed - res.Global.NewDeaths - res.Global.NewRecovered
    });

    this.isLoading = false
  }
}

<div class='main-overview'>

    <div class='overview'>
        <h4>Overview</h4>
        <div class='col-md-6 input-group'>
            <input id="typeahead-focus" type="text" class="form-control" [(ngModel)]="country"
                [ngbTypeahead]="search" (focus)="focus$.next($any($event).target.value)"
                (click)="click$.next($any($event).target.value)" #instance="ngbTypeahead"
                placeholder="Select a Country">
            <div class="input-group-append">
                <button class="form-control btn btn-outline-primary" type="button" id="button-addon2"
                    (click)="fetchDataCountry()"><mat-icon aria-hidden="false" aria-label="Example search icon">search</mat-icon></button>
            </div>
        </div>
        <div class="panel-overview">
            <div class='paper-first'>
                <div class='card-total'>
                    <span class='title'>Total Cases</span>
                    <span class='value'>{{totalConfirmed.toLocaleString('de-DE')}}</span>
                    <div class='total-new'>
                        <span class='text-new'>+{{newConfirmed.toLocaleString('de-DE')}}</span>
                    </div>
                </div>
            </div>
            <div class='paper-second'>
                <div class='card-active'>
                    <div>
                        <span class='title'>Active</span>
                        <span class='percent'>{{percentActive | number : '1.2-2'}}%</span>
                    </div>
                    <span class='value'>{{totalActive.toLocaleString('de-DE')}}</span>
                    <div class='active-new'>
                       <span class='text-new' *ngIf="newActive > 0">+</span> <span class='text-new'>{{newActive.toLocaleString('de-DE')}}</span>
                    </div>
                </div>
                <div class='card-recovered'>
                    <div>
                        <span class='title'>Recovered</span>
                        <span class='percent'>{{percentRecovered | number : '1.2-2'}}%</span>
                    </div>
                    <span class='value'>{{totalRecovered.toLocaleString('de-DE')}}</span>
                    <div class='recovered-new'>
                        <span class='text-new'>+{{newRecovered.toLocaleString('de-DE')}}</span>
                    </div>
                </div>
                <div class='card-death'>
                    <div>
                        <span class='title'>Death</span>
                        <span class='percent'>{{percentDeath | number : '1.2-2'}}%</span>
                    </div>
                    <span class='value'>{{totalDeath.toLocaleString('de-DE')}}</span>
                    <div class='death-new'>
                        <span class='text-new'>+{{newDeath.toLocaleString('de-DE')}}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class='stats'>
        <app-stats></app-stats>
    </div>



</div>
